#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x75FE259AA8AC8032 (grim@reaperworld.com)
#
Name     : pidgin
Version  : 2.12.0
Release  : 3
URL      : https://downloads.sourceforge.net/project/pidgin/Pidgin/2.12.0/pidgin-2.12.0.tar.bz2
Source0  : https://downloads.sourceforge.net/project/pidgin/Pidgin/2.12.0/pidgin-2.12.0.tar.bz2
Source99 : https://downloads.sourceforge.net/project/pidgin/Pidgin/2.12.0/pidgin-2.12.0.tar.bz2.asc
Summary  : A GTK+ based multiprotocol instant messaging client
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: pidgin-bin
Requires: pidgin-lib
Requires: pidgin-data
Requires: pidgin-locales
Requires: pidgin-doc
BuildRequires : GConf-dev
BuildRequires : ca-certs-static
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(NetworkManager)
BuildRequires : pkgconfig(check)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dbus-glib-1)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-app-1.0)
BuildRequires : pkgconfig(gstreamer-video-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(libidn)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(sm)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(x11)

%description
Pidgin allows you to talk to anyone using a variety of messaging
protocols including AIM, XMPP, Bonjour, Gadu-Gadu,
ICQ, IRC, Novell Groupwise, QQ, Lotus Sametime, SILC, Simple and
Zephyr.  These protocols are implemented using a modular, easy to
use design.  To use a protocol, just add an account using the
account editor.

Pidgin supports many common features of other clients, as well as many
unique features, such as perl scripting, TCL scripting and C plugins.

Pidgin is not affiliated with or endorsed by America Online, Inc.,
Microsoft Corporation, or ICQ Inc.

%package bin
Summary: bin components for the pidgin package.
Group: Binaries
Requires: pidgin-data

%description bin
bin components for the pidgin package.


%package data
Summary: data components for the pidgin package.
Group: Data

%description data
data components for the pidgin package.


%package dev
Summary: dev components for the pidgin package.
Group: Development
Requires: pidgin-lib
Requires: pidgin-bin
Requires: pidgin-data
Provides: pidgin-devel

%description dev
dev components for the pidgin package.


%package doc
Summary: doc components for the pidgin package.
Group: Documentation

%description doc
doc components for the pidgin package.


%package lib
Summary: lib components for the pidgin package.
Group: Libraries
Requires: pidgin-data

%description lib
lib components for the pidgin package.


%package locales
Summary: locales components for the pidgin package.
Group: Default

%description locales
locales components for the pidgin package.


%prep
%setup -q -n pidgin-2.12.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1506128154
%configure --disable-static --disable-unity --disable-mono --disable-consoleui --disable-meanwhile --disable-krb4 --disable-cyrus-sasl --disable-screensaver --disable-gtkspell --disable-vv --disable-avahi --disable-perl --disable-tcl --disable-missing-dependencies --with-system-ssl-certs=/var/cache/ca-certs/anchors
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1506128154
rm -rf %{buildroot}
%make_install
%find_lang pidgin

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pidgin
/usr/bin/purple-client-example
/usr/bin/purple-remote
/usr/bin/purple-send
/usr/bin/purple-send-async
/usr/bin/purple-url-handler

%files data
%defattr(-,root,root,-)
/usr/share/appdata/pidgin.appdata.xml
/usr/share/applications/pidgin.desktop
/usr/share/icons/hicolor/16x16/apps/pidgin.png
/usr/share/icons/hicolor/22x22/apps/pidgin.png
/usr/share/icons/hicolor/24x24/apps/pidgin.png
/usr/share/icons/hicolor/32x32/apps/pidgin.png
/usr/share/icons/hicolor/48x48/apps/pidgin.png
/usr/share/icons/hicolor/scalable/apps/pidgin.svg
/usr/share/pixmaps/pidgin/animations/16/connect0.png
/usr/share/pixmaps/pidgin/animations/16/connect1.png
/usr/share/pixmaps/pidgin/animations/16/connect2.png
/usr/share/pixmaps/pidgin/animations/16/connect3.png
/usr/share/pixmaps/pidgin/animations/16/connect4.png
/usr/share/pixmaps/pidgin/animations/16/connect5.png
/usr/share/pixmaps/pidgin/animations/16/connect6.png
/usr/share/pixmaps/pidgin/animations/16/connect7.png
/usr/share/pixmaps/pidgin/animations/16/connect8.png
/usr/share/pixmaps/pidgin/animations/16/process-working0.png
/usr/share/pixmaps/pidgin/animations/16/process-working1.png
/usr/share/pixmaps/pidgin/animations/16/process-working10.png
/usr/share/pixmaps/pidgin/animations/16/process-working11.png
/usr/share/pixmaps/pidgin/animations/16/process-working12.png
/usr/share/pixmaps/pidgin/animations/16/process-working13.png
/usr/share/pixmaps/pidgin/animations/16/process-working14.png
/usr/share/pixmaps/pidgin/animations/16/process-working15.png
/usr/share/pixmaps/pidgin/animations/16/process-working16.png
/usr/share/pixmaps/pidgin/animations/16/process-working17.png
/usr/share/pixmaps/pidgin/animations/16/process-working18.png
/usr/share/pixmaps/pidgin/animations/16/process-working19.png
/usr/share/pixmaps/pidgin/animations/16/process-working2.png
/usr/share/pixmaps/pidgin/animations/16/process-working20.png
/usr/share/pixmaps/pidgin/animations/16/process-working21.png
/usr/share/pixmaps/pidgin/animations/16/process-working22.png
/usr/share/pixmaps/pidgin/animations/16/process-working23.png
/usr/share/pixmaps/pidgin/animations/16/process-working24.png
/usr/share/pixmaps/pidgin/animations/16/process-working25.png
/usr/share/pixmaps/pidgin/animations/16/process-working26.png
/usr/share/pixmaps/pidgin/animations/16/process-working27.png
/usr/share/pixmaps/pidgin/animations/16/process-working28.png
/usr/share/pixmaps/pidgin/animations/16/process-working29.png
/usr/share/pixmaps/pidgin/animations/16/process-working3.png
/usr/share/pixmaps/pidgin/animations/16/process-working30.png
/usr/share/pixmaps/pidgin/animations/16/process-working4.png
/usr/share/pixmaps/pidgin/animations/16/process-working5.png
/usr/share/pixmaps/pidgin/animations/16/process-working6.png
/usr/share/pixmaps/pidgin/animations/16/process-working7.png
/usr/share/pixmaps/pidgin/animations/16/process-working8.png
/usr/share/pixmaps/pidgin/animations/16/process-working9.png
/usr/share/pixmaps/pidgin/animations/16/typing0.png
/usr/share/pixmaps/pidgin/animations/16/typing1.png
/usr/share/pixmaps/pidgin/animations/16/typing2.png
/usr/share/pixmaps/pidgin/animations/16/typing3.png
/usr/share/pixmaps/pidgin/animations/16/typing4.png
/usr/share/pixmaps/pidgin/animations/16/typing5.png
/usr/share/pixmaps/pidgin/arrow-down.xpm
/usr/share/pixmaps/pidgin/arrow-left.xpm
/usr/share/pixmaps/pidgin/arrow-right.xpm
/usr/share/pixmaps/pidgin/arrow-up.xpm
/usr/share/pixmaps/pidgin/buttons/edit.png
/usr/share/pixmaps/pidgin/buttons/info.png
/usr/share/pixmaps/pidgin/buttons/music.png
/usr/share/pixmaps/pidgin/buttons/pause.png
/usr/share/pixmaps/pidgin/dialogs/16/auth.png
/usr/share/pixmaps/pidgin/dialogs/16/error.png
/usr/share/pixmaps/pidgin/dialogs/16/info.png
/usr/share/pixmaps/pidgin/dialogs/16/mail.png
/usr/share/pixmaps/pidgin/dialogs/16/question.png
/usr/share/pixmaps/pidgin/dialogs/64/auth.png
/usr/share/pixmaps/pidgin/dialogs/64/cool.png
/usr/share/pixmaps/pidgin/dialogs/64/dialog.png
/usr/share/pixmaps/pidgin/dialogs/64/error.png
/usr/share/pixmaps/pidgin/dialogs/64/info.png
/usr/share/pixmaps/pidgin/dialogs/64/mail.png
/usr/share/pixmaps/pidgin/dialogs/64/question.png
/usr/share/pixmaps/pidgin/dialogs/64/warning.png
/usr/share/pixmaps/pidgin/dialogs/scalable/auth.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/cool.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/dialog.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/error.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/info.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/question.svg
/usr/share/pixmaps/pidgin/dialogs/scalable/warning.svg
/usr/share/pixmaps/pidgin/emblems/16/aol-client.png
/usr/share/pixmaps/pidgin/emblems/16/birthday.png
/usr/share/pixmaps/pidgin/emblems/16/blocked.png
/usr/share/pixmaps/pidgin/emblems/16/bot.png
/usr/share/pixmaps/pidgin/emblems/16/external.png
/usr/share/pixmaps/pidgin/emblems/16/female.png
/usr/share/pixmaps/pidgin/emblems/16/founder.png
/usr/share/pixmaps/pidgin/emblems/16/free-for-chat.png
/usr/share/pixmaps/pidgin/emblems/16/game.png
/usr/share/pixmaps/pidgin/emblems/16/half-operator.png
/usr/share/pixmaps/pidgin/emblems/16/hiptop.png
/usr/share/pixmaps/pidgin/emblems/16/male.png
/usr/share/pixmaps/pidgin/emblems/16/mobile.png
/usr/share/pixmaps/pidgin/emblems/16/not-authorized.png
/usr/share/pixmaps/pidgin/emblems/16/operator.png
/usr/share/pixmaps/pidgin/emblems/16/secure.png
/usr/share/pixmaps/pidgin/emblems/16/unavailable.png
/usr/share/pixmaps/pidgin/emblems/16/video.png
/usr/share/pixmaps/pidgin/emblems/16/voice.png
/usr/share/pixmaps/pidgin/emblems/scalable/aol-client.svg
/usr/share/pixmaps/pidgin/emblems/scalable/blocked.svg
/usr/share/pixmaps/pidgin/emblems/scalable/bot.svg
/usr/share/pixmaps/pidgin/emblems/scalable/external.svg
/usr/share/pixmaps/pidgin/emblems/scalable/female.svg
/usr/share/pixmaps/pidgin/emblems/scalable/free-for-chat.svg
/usr/share/pixmaps/pidgin/emblems/scalable/game.svg
/usr/share/pixmaps/pidgin/emblems/scalable/male.svg
/usr/share/pixmaps/pidgin/emblems/scalable/not-authorized.svg
/usr/share/pixmaps/pidgin/emblems/scalable/secure.svg
/usr/share/pixmaps/pidgin/emblems/scalable/unavailable.svg
/usr/share/pixmaps/pidgin/emblems/scalable/video.svg
/usr/share/pixmaps/pidgin/emblems/scalable/voice.svg
/usr/share/pixmaps/pidgin/emotes/default/act-up.png
/usr/share/pixmaps/pidgin/emotes/default/afraid.png
/usr/share/pixmaps/pidgin/emotes/default/airplane.png
/usr/share/pixmaps/pidgin/emotes/default/alien.png
/usr/share/pixmaps/pidgin/emotes/default/amorous.png
/usr/share/pixmaps/pidgin/emotes/default/angel.png
/usr/share/pixmaps/pidgin/emotes/default/angry.png
/usr/share/pixmaps/pidgin/emotes/default/arrogant.png
/usr/share/pixmaps/pidgin/emotes/default/at-wits-end.png
/usr/share/pixmaps/pidgin/emotes/default/bad.png
/usr/share/pixmaps/pidgin/emotes/default/bashful.png
/usr/share/pixmaps/pidgin/emotes/default/beat-up.png
/usr/share/pixmaps/pidgin/emotes/default/beauty.png
/usr/share/pixmaps/pidgin/emotes/default/beer.png
/usr/share/pixmaps/pidgin/emotes/default/blowkiss.png
/usr/share/pixmaps/pidgin/emotes/default/bomb.png
/usr/share/pixmaps/pidgin/emotes/default/bored.png
/usr/share/pixmaps/pidgin/emotes/default/bowl.png
/usr/share/pixmaps/pidgin/emotes/default/boy.png
/usr/share/pixmaps/pidgin/emotes/default/brb.png
/usr/share/pixmaps/pidgin/emotes/default/bulgy-eyes.png
/usr/share/pixmaps/pidgin/emotes/default/bunny.png
/usr/share/pixmaps/pidgin/emotes/default/bye.png
/usr/share/pixmaps/pidgin/emotes/default/cake.png
/usr/share/pixmaps/pidgin/emotes/default/call-me.png
/usr/share/pixmaps/pidgin/emotes/default/camera.png
/usr/share/pixmaps/pidgin/emotes/default/can.png
/usr/share/pixmaps/pidgin/emotes/default/car.png
/usr/share/pixmaps/pidgin/emotes/default/cat.png
/usr/share/pixmaps/pidgin/emotes/default/chicken.png
/usr/share/pixmaps/pidgin/emotes/default/chilli.png
/usr/share/pixmaps/pidgin/emotes/default/cigarette.png
/usr/share/pixmaps/pidgin/emotes/default/clap.png
/usr/share/pixmaps/pidgin/emotes/default/clock.png
/usr/share/pixmaps/pidgin/emotes/default/cloudy.png
/usr/share/pixmaps/pidgin/emotes/default/clover.png
/usr/share/pixmaps/pidgin/emotes/default/clown.png
/usr/share/pixmaps/pidgin/emotes/default/coffee.png
/usr/share/pixmaps/pidgin/emotes/default/coins.png
/usr/share/pixmaps/pidgin/emotes/default/cold.png
/usr/share/pixmaps/pidgin/emotes/default/computer.png
/usr/share/pixmaps/pidgin/emotes/default/confused.png
/usr/share/pixmaps/pidgin/emotes/default/console.png
/usr/share/pixmaps/pidgin/emotes/default/cow.png
/usr/share/pixmaps/pidgin/emotes/default/cowboy.png
/usr/share/pixmaps/pidgin/emotes/default/crying.png
/usr/share/pixmaps/pidgin/emotes/default/curl-lip.png
/usr/share/pixmaps/pidgin/emotes/default/curse.png
/usr/share/pixmaps/pidgin/emotes/default/cute.png
/usr/share/pixmaps/pidgin/emotes/default/cyclops.png
/usr/share/pixmaps/pidgin/emotes/default/dance.png
/usr/share/pixmaps/pidgin/emotes/default/dazed.png
/usr/share/pixmaps/pidgin/emotes/default/desire.png
/usr/share/pixmaps/pidgin/emotes/default/devil.png
/usr/share/pixmaps/pidgin/emotes/default/disappointed.png
/usr/share/pixmaps/pidgin/emotes/default/disdain.png
/usr/share/pixmaps/pidgin/emotes/default/doctor.png
/usr/share/pixmaps/pidgin/emotes/default/dog.png
/usr/share/pixmaps/pidgin/emotes/default/doh.png
/usr/share/pixmaps/pidgin/emotes/default/dont-know.png
/usr/share/pixmaps/pidgin/emotes/default/drink.png
/usr/share/pixmaps/pidgin/emotes/default/drool.png
/usr/share/pixmaps/pidgin/emotes/default/embarrassed.png
/usr/share/pixmaps/pidgin/emotes/default/excited.png
/usr/share/pixmaps/pidgin/emotes/default/excruciating.png
/usr/share/pixmaps/pidgin/emotes/default/eyeroll.png
/usr/share/pixmaps/pidgin/emotes/default/female-fighter.png
/usr/share/pixmaps/pidgin/emotes/default/film.png
/usr/share/pixmaps/pidgin/emotes/default/fingers-crossed.png
/usr/share/pixmaps/pidgin/emotes/default/flag.png
/usr/share/pixmaps/pidgin/emotes/default/foot-in-mouth.png
/usr/share/pixmaps/pidgin/emotes/default/freaked-out.png
/usr/share/pixmaps/pidgin/emotes/default/ghost.png
/usr/share/pixmaps/pidgin/emotes/default/giggle.png
/usr/share/pixmaps/pidgin/emotes/default/girl.png
/usr/share/pixmaps/pidgin/emotes/default/glasses-cool.png
/usr/share/pixmaps/pidgin/emotes/default/glasses-nerdy.png
/usr/share/pixmaps/pidgin/emotes/default/go-away.png
/usr/share/pixmaps/pidgin/emotes/default/goat.png
/usr/share/pixmaps/pidgin/emotes/default/good.png
/usr/share/pixmaps/pidgin/emotes/default/hammer.png
/usr/share/pixmaps/pidgin/emotes/default/handcuffs.png
/usr/share/pixmaps/pidgin/emotes/default/handshake.png
/usr/share/pixmaps/pidgin/emotes/default/happy.png
/usr/share/pixmaps/pidgin/emotes/default/highfive.png
/usr/share/pixmaps/pidgin/emotes/default/hot.png
/usr/share/pixmaps/pidgin/emotes/default/hug-left.png
/usr/share/pixmaps/pidgin/emotes/default/hug-right.png
/usr/share/pixmaps/pidgin/emotes/default/hungry.png
/usr/share/pixmaps/pidgin/emotes/default/hypnotized.png
/usr/share/pixmaps/pidgin/emotes/default/in_love.png
/usr/share/pixmaps/pidgin/emotes/default/island.png
/usr/share/pixmaps/pidgin/emotes/default/jump.png
/usr/share/pixmaps/pidgin/emotes/default/kiss.png
/usr/share/pixmaps/pidgin/emotes/default/kissed.png
/usr/share/pixmaps/pidgin/emotes/default/kissing.png
/usr/share/pixmaps/pidgin/emotes/default/knife.png
/usr/share/pixmaps/pidgin/emotes/default/lamp.png
/usr/share/pixmaps/pidgin/emotes/default/lashes.png
/usr/share/pixmaps/pidgin/emotes/default/laugh.png
/usr/share/pixmaps/pidgin/emotes/default/liquor.png
/usr/share/pixmaps/pidgin/emotes/default/loser.png
/usr/share/pixmaps/pidgin/emotes/default/love-over.png
/usr/share/pixmaps/pidgin/emotes/default/lying.png
/usr/share/pixmaps/pidgin/emotes/default/mad-tongue.png
/usr/share/pixmaps/pidgin/emotes/default/mail.png
/usr/share/pixmaps/pidgin/emotes/default/male-fighter1.png
/usr/share/pixmaps/pidgin/emotes/default/male-fighter2.png
/usr/share/pixmaps/pidgin/emotes/default/mean.png
/usr/share/pixmaps/pidgin/emotes/default/meeting.png
/usr/share/pixmaps/pidgin/emotes/default/messed.png
/usr/share/pixmaps/pidgin/emotes/default/mobile.png
/usr/share/pixmaps/pidgin/emotes/default/mohawk.png
/usr/share/pixmaps/pidgin/emotes/default/moneymouth.png
/usr/share/pixmaps/pidgin/emotes/default/monkey.png
/usr/share/pixmaps/pidgin/emotes/default/moon.png
/usr/share/pixmaps/pidgin/emotes/default/mrgreen.png
/usr/share/pixmaps/pidgin/emotes/default/music.png
/usr/share/pixmaps/pidgin/emotes/default/musical-note.png
/usr/share/pixmaps/pidgin/emotes/default/nervous.png
/usr/share/pixmaps/pidgin/emotes/default/neutral.png
/usr/share/pixmaps/pidgin/emotes/default/on-the-phone.png
/usr/share/pixmaps/pidgin/emotes/default/party.png
/usr/share/pixmaps/pidgin/emotes/default/peace.png
/usr/share/pixmaps/pidgin/emotes/default/phone.png
/usr/share/pixmaps/pidgin/emotes/default/pig.png
/usr/share/pixmaps/pidgin/emotes/default/pill.png
/usr/share/pixmaps/pidgin/emotes/default/pirate.png
/usr/share/pixmaps/pidgin/emotes/default/pissed-off.png
/usr/share/pixmaps/pidgin/emotes/default/pizza.png
/usr/share/pixmaps/pidgin/emotes/default/plate.png
/usr/share/pixmaps/pidgin/emotes/default/poop.png
/usr/share/pixmaps/pidgin/emotes/default/pray.png
/usr/share/pixmaps/pidgin/emotes/default/present.png
/usr/share/pixmaps/pidgin/emotes/default/pumpkin.png
/usr/share/pixmaps/pidgin/emotes/default/question.png
/usr/share/pixmaps/pidgin/emotes/default/quiet.png
/usr/share/pixmaps/pidgin/emotes/default/rain.png
/usr/share/pixmaps/pidgin/emotes/default/rainbow.png
/usr/share/pixmaps/pidgin/emotes/default/rose-dead.png
/usr/share/pixmaps/pidgin/emotes/default/rose.png
/usr/share/pixmaps/pidgin/emotes/default/rotfl.png
/usr/share/pixmaps/pidgin/emotes/default/sad.png
/usr/share/pixmaps/pidgin/emotes/default/sarcastic.png
/usr/share/pixmaps/pidgin/emotes/default/search.png
/usr/share/pixmaps/pidgin/emotes/default/secret.png
/usr/share/pixmaps/pidgin/emotes/default/shame.png
/usr/share/pixmaps/pidgin/emotes/default/sheep.png
/usr/share/pixmaps/pidgin/emotes/default/shocked.png
/usr/share/pixmaps/pidgin/emotes/default/shout.png
/usr/share/pixmaps/pidgin/emotes/default/shut-mouth.png
/usr/share/pixmaps/pidgin/emotes/default/sick.png
/usr/share/pixmaps/pidgin/emotes/default/sidefrown.png
/usr/share/pixmaps/pidgin/emotes/default/silly.png
/usr/share/pixmaps/pidgin/emotes/default/sinister.png
/usr/share/pixmaps/pidgin/emotes/default/skeleton.png
/usr/share/pixmaps/pidgin/emotes/default/skywalker.png
/usr/share/pixmaps/pidgin/emotes/default/sleeping.png
/usr/share/pixmaps/pidgin/emotes/default/sleepy.png
/usr/share/pixmaps/pidgin/emotes/default/smirk.png
/usr/share/pixmaps/pidgin/emotes/default/snail.png
/usr/share/pixmaps/pidgin/emotes/default/snicker.png
/usr/share/pixmaps/pidgin/emotes/default/snowman.png
/usr/share/pixmaps/pidgin/emotes/default/soccerball.png
/usr/share/pixmaps/pidgin/emotes/default/soldier.png
/usr/share/pixmaps/pidgin/emotes/default/star.png
/usr/share/pixmaps/pidgin/emotes/default/starving.png
/usr/share/pixmaps/pidgin/emotes/default/stop.png
/usr/share/pixmaps/pidgin/emotes/default/stressed.png
/usr/share/pixmaps/pidgin/emotes/default/struggle.png
/usr/share/pixmaps/pidgin/emotes/default/sun.png
/usr/share/pixmaps/pidgin/emotes/default/talktohand.png
/usr/share/pixmaps/pidgin/emotes/default/teeth.png
/usr/share/pixmaps/pidgin/emotes/default/terror.png
/usr/share/pixmaps/pidgin/emotes/default/theme
/usr/share/pixmaps/pidgin/emotes/default/thinking.png
/usr/share/pixmaps/pidgin/emotes/default/thunder.png
/usr/share/pixmaps/pidgin/emotes/default/time-out.png
/usr/share/pixmaps/pidgin/emotes/default/tongue.png
/usr/share/pixmaps/pidgin/emotes/default/turtle.png
/usr/share/pixmaps/pidgin/emotes/default/tv.png
/usr/share/pixmaps/pidgin/emotes/default/umbrella.png
/usr/share/pixmaps/pidgin/emotes/default/vampire.png
/usr/share/pixmaps/pidgin/emotes/default/victory.png
/usr/share/pixmaps/pidgin/emotes/default/waiting.png
/usr/share/pixmaps/pidgin/emotes/default/watermelon.png
/usr/share/pixmaps/pidgin/emotes/default/waving.png
/usr/share/pixmaps/pidgin/emotes/default/weep.png
/usr/share/pixmaps/pidgin/emotes/default/wilt.png
/usr/share/pixmaps/pidgin/emotes/default/wink.png
/usr/share/pixmaps/pidgin/emotes/default/worship.png
/usr/share/pixmaps/pidgin/emotes/default/yin-yang.png
/usr/share/pixmaps/pidgin/emotes/none/theme
/usr/share/pixmaps/pidgin/emotes/small/afraid.png
/usr/share/pixmaps/pidgin/emotes/small/amorous.png
/usr/share/pixmaps/pidgin/emotes/small/angel.png
/usr/share/pixmaps/pidgin/emotes/small/angry.png
/usr/share/pixmaps/pidgin/emotes/small/bathing.png
/usr/share/pixmaps/pidgin/emotes/small/beer.png
/usr/share/pixmaps/pidgin/emotes/small/bored.png
/usr/share/pixmaps/pidgin/emotes/small/boy.png
/usr/share/pixmaps/pidgin/emotes/small/camera.png
/usr/share/pixmaps/pidgin/emotes/small/chilli.png
/usr/share/pixmaps/pidgin/emotes/small/cigarette.png
/usr/share/pixmaps/pidgin/emotes/small/cinema.png
/usr/share/pixmaps/pidgin/emotes/small/coffee.png
/usr/share/pixmaps/pidgin/emotes/small/cold.png
/usr/share/pixmaps/pidgin/emotes/small/confused.png
/usr/share/pixmaps/pidgin/emotes/small/console.png
/usr/share/pixmaps/pidgin/emotes/small/cross.png
/usr/share/pixmaps/pidgin/emotes/small/crying.png
/usr/share/pixmaps/pidgin/emotes/small/devil.png
/usr/share/pixmaps/pidgin/emotes/small/disappointed.png
/usr/share/pixmaps/pidgin/emotes/small/dont-know.png
/usr/share/pixmaps/pidgin/emotes/small/drool.png
/usr/share/pixmaps/pidgin/emotes/small/embarrassed.png
/usr/share/pixmaps/pidgin/emotes/small/excited.png
/usr/share/pixmaps/pidgin/emotes/small/excruciating.png
/usr/share/pixmaps/pidgin/emotes/small/eyeroll.png
/usr/share/pixmaps/pidgin/emotes/small/girl.png
/usr/share/pixmaps/pidgin/emotes/small/grumpy.png
/usr/share/pixmaps/pidgin/emotes/small/happy.png
/usr/share/pixmaps/pidgin/emotes/small/hot.png
/usr/share/pixmaps/pidgin/emotes/small/hug-left.png
/usr/share/pixmaps/pidgin/emotes/small/hug-right.png
/usr/share/pixmaps/pidgin/emotes/small/hungry.png
/usr/share/pixmaps/pidgin/emotes/small/in_love.png
/usr/share/pixmaps/pidgin/emotes/small/internet.png
/usr/share/pixmaps/pidgin/emotes/small/invincible.png
/usr/share/pixmaps/pidgin/emotes/small/kiss.png
/usr/share/pixmaps/pidgin/emotes/small/lamp.png
/usr/share/pixmaps/pidgin/emotes/small/lying.png
/usr/share/pixmaps/pidgin/emotes/small/meeting.png
/usr/share/pixmaps/pidgin/emotes/small/mobile.png
/usr/share/pixmaps/pidgin/emotes/small/mrgreen.png
/usr/share/pixmaps/pidgin/emotes/small/music.png
/usr/share/pixmaps/pidgin/emotes/small/musical-note.png
/usr/share/pixmaps/pidgin/emotes/small/nerdy.png
/usr/share/pixmaps/pidgin/emotes/small/neutral.png
/usr/share/pixmaps/pidgin/emotes/small/party.png
/usr/share/pixmaps/pidgin/emotes/small/phone.png
/usr/share/pixmaps/pidgin/emotes/small/pirate.png
/usr/share/pixmaps/pidgin/emotes/small/pissed-off.png
/usr/share/pixmaps/pidgin/emotes/small/plate.png
/usr/share/pixmaps/pidgin/emotes/small/question.png
/usr/share/pixmaps/pidgin/emotes/small/restroom.png
/usr/share/pixmaps/pidgin/emotes/small/rose.png
/usr/share/pixmaps/pidgin/emotes/small/sad.png
/usr/share/pixmaps/pidgin/emotes/small/search.png
/usr/share/pixmaps/pidgin/emotes/small/shame.png
/usr/share/pixmaps/pidgin/emotes/small/shocked.png
/usr/share/pixmaps/pidgin/emotes/small/shopping.png
/usr/share/pixmaps/pidgin/emotes/small/shut-mouth.png
/usr/share/pixmaps/pidgin/emotes/small/sick.png
/usr/share/pixmaps/pidgin/emotes/small/silent.png
/usr/share/pixmaps/pidgin/emotes/small/sleeping.png
/usr/share/pixmaps/pidgin/emotes/small/sleepy.png
/usr/share/pixmaps/pidgin/emotes/small/star.png
/usr/share/pixmaps/pidgin/emotes/small/stressed.png
/usr/share/pixmaps/pidgin/emotes/small/studying.png
/usr/share/pixmaps/pidgin/emotes/small/suit.png
/usr/share/pixmaps/pidgin/emotes/small/surfing.png
/usr/share/pixmaps/pidgin/emotes/small/theme
/usr/share/pixmaps/pidgin/emotes/small/thinking.png
/usr/share/pixmaps/pidgin/emotes/small/thunder.png
/usr/share/pixmaps/pidgin/emotes/small/tongue.png
/usr/share/pixmaps/pidgin/emotes/small/tv.png
/usr/share/pixmaps/pidgin/emotes/small/typing.png
/usr/share/pixmaps/pidgin/emotes/small/uhm-yeah.png
/usr/share/pixmaps/pidgin/emotes/small/wink.png
/usr/share/pixmaps/pidgin/emotes/small/working.png
/usr/share/pixmaps/pidgin/emotes/small/writing.png
/usr/share/pixmaps/pidgin/logo.png
/usr/share/pixmaps/pidgin/protocols/16/aim.png
/usr/share/pixmaps/pidgin/protocols/16/bonjour.png
/usr/share/pixmaps/pidgin/protocols/16/facebook.png
/usr/share/pixmaps/pidgin/protocols/16/gadu-gadu.png
/usr/share/pixmaps/pidgin/protocols/16/google-talk.png
/usr/share/pixmaps/pidgin/protocols/16/icq.png
/usr/share/pixmaps/pidgin/protocols/16/irc.png
/usr/share/pixmaps/pidgin/protocols/16/jabber.png
/usr/share/pixmaps/pidgin/protocols/16/meanwhile.png
/usr/share/pixmaps/pidgin/protocols/16/novell.png
/usr/share/pixmaps/pidgin/protocols/16/silc.png
/usr/share/pixmaps/pidgin/protocols/16/simple.png
/usr/share/pixmaps/pidgin/protocols/16/zephyr.png
/usr/share/pixmaps/pidgin/protocols/22/aim.png
/usr/share/pixmaps/pidgin/protocols/22/bonjour.png
/usr/share/pixmaps/pidgin/protocols/22/facebook.png
/usr/share/pixmaps/pidgin/protocols/22/gadu-gadu.png
/usr/share/pixmaps/pidgin/protocols/22/google-talk.png
/usr/share/pixmaps/pidgin/protocols/22/icq.png
/usr/share/pixmaps/pidgin/protocols/22/irc.png
/usr/share/pixmaps/pidgin/protocols/22/jabber.png
/usr/share/pixmaps/pidgin/protocols/22/meanwhile.png
/usr/share/pixmaps/pidgin/protocols/22/novell.png
/usr/share/pixmaps/pidgin/protocols/22/silc.png
/usr/share/pixmaps/pidgin/protocols/22/simple.png
/usr/share/pixmaps/pidgin/protocols/22/zephyr.png
/usr/share/pixmaps/pidgin/protocols/48/aim.png
/usr/share/pixmaps/pidgin/protocols/48/bonjour.png
/usr/share/pixmaps/pidgin/protocols/48/facebook.png
/usr/share/pixmaps/pidgin/protocols/48/gadu-gadu.png
/usr/share/pixmaps/pidgin/protocols/48/icq.png
/usr/share/pixmaps/pidgin/protocols/48/irc.png
/usr/share/pixmaps/pidgin/protocols/48/jabber.png
/usr/share/pixmaps/pidgin/protocols/48/meanwhile.png
/usr/share/pixmaps/pidgin/protocols/48/novell.png
/usr/share/pixmaps/pidgin/protocols/48/silc.png
/usr/share/pixmaps/pidgin/protocols/48/simple.png
/usr/share/pixmaps/pidgin/protocols/48/zephyr.png
/usr/share/pixmaps/pidgin/protocols/scalable/aim.svg
/usr/share/pixmaps/pidgin/protocols/scalable/bonjour.svg
/usr/share/pixmaps/pidgin/protocols/scalable/gadu-gadu.svg
/usr/share/pixmaps/pidgin/protocols/scalable/google-talk.svg
/usr/share/pixmaps/pidgin/protocols/scalable/icq.svg
/usr/share/pixmaps/pidgin/protocols/scalable/irc.svg
/usr/share/pixmaps/pidgin/protocols/scalable/jabber.svg
/usr/share/pixmaps/pidgin/protocols/scalable/meanwhile.svg
/usr/share/pixmaps/pidgin/protocols/scalable/novell.svg
/usr/share/pixmaps/pidgin/protocols/scalable/silc.svg
/usr/share/pixmaps/pidgin/protocols/scalable/simple.svg
/usr/share/pixmaps/pidgin/protocols/scalable/zephyr.svg
/usr/share/pixmaps/pidgin/status/11/available.png
/usr/share/pixmaps/pidgin/status/11/away.png
/usr/share/pixmaps/pidgin/status/11/busy.png
/usr/share/pixmaps/pidgin/status/11/chat.png
/usr/share/pixmaps/pidgin/status/11/extended-away.png
/usr/share/pixmaps/pidgin/status/11/invisible.png
/usr/share/pixmaps/pidgin/status/11/log-in.png
/usr/share/pixmaps/pidgin/status/11/log-out.png
/usr/share/pixmaps/pidgin/status/11/offline.png
/usr/share/pixmaps/pidgin/status/11/person.png
/usr/share/pixmaps/pidgin/status/11/rtl/extended-away.png
/usr/share/pixmaps/pidgin/status/11/rtl/log-in.png
/usr/share/pixmaps/pidgin/status/11/rtl/log-out.png
/usr/share/pixmaps/pidgin/status/16/available.png
/usr/share/pixmaps/pidgin/status/16/away.png
/usr/share/pixmaps/pidgin/status/16/busy.png
/usr/share/pixmaps/pidgin/status/16/chat.png
/usr/share/pixmaps/pidgin/status/16/extended-away.png
/usr/share/pixmaps/pidgin/status/16/invisible.png
/usr/share/pixmaps/pidgin/status/16/log-in.png
/usr/share/pixmaps/pidgin/status/16/log-out.png
/usr/share/pixmaps/pidgin/status/16/offline.png
/usr/share/pixmaps/pidgin/status/16/person.png
/usr/share/pixmaps/pidgin/status/16/rtl/extended-away.png
/usr/share/pixmaps/pidgin/status/16/rtl/log-in.png
/usr/share/pixmaps/pidgin/status/16/rtl/log-out.png
/usr/share/pixmaps/pidgin/status/22/available.png
/usr/share/pixmaps/pidgin/status/22/away.png
/usr/share/pixmaps/pidgin/status/22/busy.png
/usr/share/pixmaps/pidgin/status/22/chat.png
/usr/share/pixmaps/pidgin/status/22/extended-away.png
/usr/share/pixmaps/pidgin/status/22/invisible.png
/usr/share/pixmaps/pidgin/status/22/log-in.png
/usr/share/pixmaps/pidgin/status/22/log-out.png
/usr/share/pixmaps/pidgin/status/22/offline.png
/usr/share/pixmaps/pidgin/status/22/person.png
/usr/share/pixmaps/pidgin/status/22/rtl/extended-away.png
/usr/share/pixmaps/pidgin/status/22/rtl/log-in.png
/usr/share/pixmaps/pidgin/status/22/rtl/log-out.png
/usr/share/pixmaps/pidgin/status/32/available.png
/usr/share/pixmaps/pidgin/status/32/away.png
/usr/share/pixmaps/pidgin/status/32/busy.png
/usr/share/pixmaps/pidgin/status/32/chat.png
/usr/share/pixmaps/pidgin/status/32/extended-away.png
/usr/share/pixmaps/pidgin/status/32/invisible.png
/usr/share/pixmaps/pidgin/status/32/log-in.png
/usr/share/pixmaps/pidgin/status/32/log-out.png
/usr/share/pixmaps/pidgin/status/32/offline.png
/usr/share/pixmaps/pidgin/status/32/person.png
/usr/share/pixmaps/pidgin/status/32/rtl/extended-away.png
/usr/share/pixmaps/pidgin/status/32/rtl/log-in.png
/usr/share/pixmaps/pidgin/status/32/rtl/log-out.png
/usr/share/pixmaps/pidgin/status/48/available.png
/usr/share/pixmaps/pidgin/status/48/away.png
/usr/share/pixmaps/pidgin/status/48/busy.png
/usr/share/pixmaps/pidgin/status/48/chat.png
/usr/share/pixmaps/pidgin/status/48/extended-away.png
/usr/share/pixmaps/pidgin/status/48/invisible.png
/usr/share/pixmaps/pidgin/status/48/log-in.png
/usr/share/pixmaps/pidgin/status/48/log-out.png
/usr/share/pixmaps/pidgin/status/48/offline.png
/usr/share/pixmaps/pidgin/status/48/person.png
/usr/share/pixmaps/pidgin/status/48/rtl/extended-away.png
/usr/share/pixmaps/pidgin/status/48/rtl/log-in.png
/usr/share/pixmaps/pidgin/status/48/rtl/log-out.png
/usr/share/pixmaps/pidgin/toolbar/11/message-new.png
/usr/share/pixmaps/pidgin/toolbar/16/audio-call.png
/usr/share/pixmaps/pidgin/toolbar/16/change-bgcolor.png
/usr/share/pixmaps/pidgin/toolbar/16/change-fgcolor.png
/usr/share/pixmaps/pidgin/toolbar/16/emote-select.png
/usr/share/pixmaps/pidgin/toolbar/16/font-face.png
/usr/share/pixmaps/pidgin/toolbar/16/font-size-down.png
/usr/share/pixmaps/pidgin/toolbar/16/font-size-up.png
/usr/share/pixmaps/pidgin/toolbar/16/get-attention.png
/usr/share/pixmaps/pidgin/toolbar/16/insert-image.png
/usr/share/pixmaps/pidgin/toolbar/16/insert-link.png
/usr/share/pixmaps/pidgin/toolbar/16/insert.png
/usr/share/pixmaps/pidgin/toolbar/16/message-new.png
/usr/share/pixmaps/pidgin/toolbar/16/plugins.png
/usr/share/pixmaps/pidgin/toolbar/16/send-file.png
/usr/share/pixmaps/pidgin/toolbar/16/transfer.png
/usr/share/pixmaps/pidgin/toolbar/16/unblock.png
/usr/share/pixmaps/pidgin/toolbar/16/video-call.png
/usr/share/pixmaps/pidgin/toolbar/22/audio-call.png
/usr/share/pixmaps/pidgin/toolbar/22/select-avatar.png
/usr/share/pixmaps/pidgin/toolbar/22/video-call.png
/usr/share/pixmaps/pidgin/toolbar/32/audio-call.png
/usr/share/pixmaps/pidgin/toolbar/32/video-call.png
/usr/share/pixmaps/pidgin/toolbar/48/audio-call.png
/usr/share/pixmaps/pidgin/toolbar/48/video-call.png
/usr/share/pixmaps/pidgin/tray/16/available_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/away_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/busy_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/connecting_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/extended-away_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/invisible_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/message_4bit.ico
/usr/share/pixmaps/pidgin/tray/16/offline_4bit.ico
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-available.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-away.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-busy.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-connect.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-email.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-invisible.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-offline.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-pending.png
/usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/pidgin-tray-xa.png
/usr/share/pixmaps/pidgin/tray/hicolor/index.theme
/usr/share/sounds/purple/alert.wav
/usr/share/sounds/purple/login.wav
/usr/share/sounds/purple/logout.wav
/usr/share/sounds/purple/receive.wav
/usr/share/sounds/purple/send.wav

%files dev
%defattr(-,root,root,-)
/usr/include/libpurple/account.h
/usr/include/libpurple/accountopt.h
/usr/include/libpurple/blist.h
/usr/include/libpurple/buddyicon.h
/usr/include/libpurple/certificate.h
/usr/include/libpurple/cipher.h
/usr/include/libpurple/circbuffer.h
/usr/include/libpurple/cmds.h
/usr/include/libpurple/connection.h
/usr/include/libpurple/conversation.h
/usr/include/libpurple/core.h
/usr/include/libpurple/dbus-bindings.h
/usr/include/libpurple/dbus-define-api.h
/usr/include/libpurple/dbus-maybe.h
/usr/include/libpurple/dbus-purple.h
/usr/include/libpurple/dbus-server.h
/usr/include/libpurple/dbus-types.h
/usr/include/libpurple/dbus-useful.h
/usr/include/libpurple/debug.h
/usr/include/libpurple/desktopitem.h
/usr/include/libpurple/dnsquery.h
/usr/include/libpurple/dnssrv.h
/usr/include/libpurple/eventloop.h
/usr/include/libpurple/ft.h
/usr/include/libpurple/gaim-compat.h
/usr/include/libpurple/idle.h
/usr/include/libpurple/imgstore.h
/usr/include/libpurple/log.h
/usr/include/libpurple/marshallers.h
/usr/include/libpurple/media-gst.h
/usr/include/libpurple/media.h
/usr/include/libpurple/media/backend-iface.h
/usr/include/libpurple/media/candidate.h
/usr/include/libpurple/media/codec.h
/usr/include/libpurple/media/enum-types.h
/usr/include/libpurple/mediamanager.h
/usr/include/libpurple/mime.h
/usr/include/libpurple/nat-pmp.h
/usr/include/libpurple/network.h
/usr/include/libpurple/notify.h
/usr/include/libpurple/ntlm.h
/usr/include/libpurple/plugin.h
/usr/include/libpurple/pluginpref.h
/usr/include/libpurple/pounce.h
/usr/include/libpurple/prefs.h
/usr/include/libpurple/privacy.h
/usr/include/libpurple/proxy.h
/usr/include/libpurple/prpl.h
/usr/include/libpurple/purple.h
/usr/include/libpurple/request.h
/usr/include/libpurple/roomlist.h
/usr/include/libpurple/savedstatuses.h
/usr/include/libpurple/server.h
/usr/include/libpurple/signals.h
/usr/include/libpurple/smiley.h
/usr/include/libpurple/sound-theme-loader.h
/usr/include/libpurple/sound-theme.h
/usr/include/libpurple/sound.h
/usr/include/libpurple/sslconn.h
/usr/include/libpurple/status.h
/usr/include/libpurple/stringref.h
/usr/include/libpurple/stun.h
/usr/include/libpurple/theme-loader.h
/usr/include/libpurple/theme-manager.h
/usr/include/libpurple/theme.h
/usr/include/libpurple/upnp.h
/usr/include/libpurple/util.h
/usr/include/libpurple/value.h
/usr/include/libpurple/version.h
/usr/include/libpurple/whiteboard.h
/usr/include/libpurple/xmlnode.h
/usr/include/pidgin/gtkaccount.h
/usr/include/pidgin/gtkblist-theme-loader.h
/usr/include/pidgin/gtkblist-theme.h
/usr/include/pidgin/gtkblist.h
/usr/include/pidgin/gtkcellrendererexpander.h
/usr/include/pidgin/gtkcertmgr.h
/usr/include/pidgin/gtkconn.h
/usr/include/pidgin/gtkconv.h
/usr/include/pidgin/gtkconvwin.h
/usr/include/pidgin/gtkdebug.h
/usr/include/pidgin/gtkdialogs.h
/usr/include/pidgin/gtkdnd-hints.h
/usr/include/pidgin/gtkdocklet.h
/usr/include/pidgin/gtkeventloop.h
/usr/include/pidgin/gtkft.h
/usr/include/pidgin/gtkgaim-compat.h
/usr/include/pidgin/gtkicon-theme-loader.h
/usr/include/pidgin/gtkicon-theme.h
/usr/include/pidgin/gtkidle.h
/usr/include/pidgin/gtkimhtml.h
/usr/include/pidgin/gtkimhtmltoolbar.h
/usr/include/pidgin/gtklog.h
/usr/include/pidgin/gtkmedia.h
/usr/include/pidgin/gtkmenutray.h
/usr/include/pidgin/gtknickcolors.h
/usr/include/pidgin/gtknotify.h
/usr/include/pidgin/gtkplugin.h
/usr/include/pidgin/gtkpluginpref.h
/usr/include/pidgin/gtkpounce.h
/usr/include/pidgin/gtkprefs.h
/usr/include/pidgin/gtkprivacy.h
/usr/include/pidgin/gtkrequest.h
/usr/include/pidgin/gtkroomlist.h
/usr/include/pidgin/gtksavedstatuses.h
/usr/include/pidgin/gtkscrollbook.h
/usr/include/pidgin/gtksession.h
/usr/include/pidgin/gtksmiley.h
/usr/include/pidgin/gtksound.h
/usr/include/pidgin/gtksourceiter.h
/usr/include/pidgin/gtksourceundomanager.h
/usr/include/pidgin/gtksourceview-marshal.h
/usr/include/pidgin/gtkstatus-icon-theme.h
/usr/include/pidgin/gtkstatusbox.h
/usr/include/pidgin/gtkthemes.h
/usr/include/pidgin/gtkutils.h
/usr/include/pidgin/gtkwhiteboard.h
/usr/include/pidgin/minidialog.h
/usr/include/pidgin/pidgin.h
/usr/include/pidgin/pidginstock.h
/usr/include/pidgin/pidgintooltip.h
/usr/lib64/libpurple-client.so
/usr/lib64/libpurple.so
/usr/lib64/pkgconfig/pidgin.pc
/usr/lib64/pkgconfig/purple.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpurple-client.so.0
/usr/lib64/libpurple-client.so.0.12.0
/usr/lib64/libpurple.so.0
/usr/lib64/libpurple.so.0.12.0
/usr/lib64/pidgin/convcolors.so
/usr/lib64/pidgin/extplacement.so
/usr/lib64/pidgin/gestures.so
/usr/lib64/pidgin/gtkbuddynote.so
/usr/lib64/pidgin/history.so
/usr/lib64/pidgin/iconaway.so
/usr/lib64/pidgin/markerline.so
/usr/lib64/pidgin/musicmessaging.so
/usr/lib64/pidgin/notify.so
/usr/lib64/pidgin/pidginrc.so
/usr/lib64/pidgin/relnot.so
/usr/lib64/pidgin/sendbutton.so
/usr/lib64/pidgin/spellchk.so
/usr/lib64/pidgin/themeedit.so
/usr/lib64/pidgin/ticker.so
/usr/lib64/pidgin/timestamp.so
/usr/lib64/pidgin/timestamp_format.so
/usr/lib64/pidgin/xmppconsole.so
/usr/lib64/pidgin/xmppdisco.so
/usr/lib64/purple-2/autoaccept.so
/usr/lib64/purple-2/buddynote.so
/usr/lib64/purple-2/dbus-example.so
/usr/lib64/purple-2/idle.so
/usr/lib64/purple-2/joinpart.so
/usr/lib64/purple-2/libaim.so
/usr/lib64/purple-2/libgg.so
/usr/lib64/purple-2/libicq.so
/usr/lib64/purple-2/libirc.so
/usr/lib64/purple-2/libjabber.so
/usr/lib64/purple-2/libjabber.so.0
/usr/lib64/purple-2/libjabber.so.0.0.0
/usr/lib64/purple-2/libnovell.so
/usr/lib64/purple-2/liboscar.so
/usr/lib64/purple-2/liboscar.so.0
/usr/lib64/purple-2/liboscar.so.0.0.0
/usr/lib64/purple-2/libsimple.so
/usr/lib64/purple-2/libxmpp.so
/usr/lib64/purple-2/libzephyr.so
/usr/lib64/purple-2/log_reader.so
/usr/lib64/purple-2/newline.so
/usr/lib64/purple-2/nss-prefs.so
/usr/lib64/purple-2/offlinemsg.so
/usr/lib64/purple-2/psychic.so
/usr/lib64/purple-2/ssl-gnutls.so
/usr/lib64/purple-2/ssl-nss.so
/usr/lib64/purple-2/ssl.so
/usr/lib64/purple-2/statenotify.so

%files locales -f pidgin.lang
%defattr(-,root,root,-)

